### ISSUE TITLE
How to communicate between component and timer-worker ?

### ISSUE THREAD

**Issue by davvoz** [chrisguttandin/worker-timers#153]
Hi dude.
I'm pretty sure this is not an issues...anyway.
Speaking about CPU , I tried your worker-timers and I realized that is more cheaper than normal setTimeout() , this is great.
But I can not connect a component (...or probably I'm not capable) , let me explain.
I have an app-component that use a timer-service that implement your timer-workers.
I want to recive the tick from the timer-service in the app-component and assign it to a variable.
In my timer-service i have this method that I partially copied from the web : 
`private scheduleNote() {
        let contextPlayTime;
        let currentTime = this.audioContext.currentTime;
        currentTime -= this.startTime;
        while (this.noteTime < currentTime + 0.200) {
            contextPlayTime = this.noteTime + this.startTime;
            this.changeStateTrack(contextPlayTime);
            this.nextNote();
        }
        this.timer = workerTimers.setTimeout(this.scheduleNote.bind(this), 0);
    }
`
I normally  use a BehaviorSubject in timer-service and a Subscription in the app-component so i can comunicate between this 2 friends .Using this metohd , without worker-timers everything is alright ... excluding the cpu.
So in my app-component:
`ngOnInit(): void {
        this.subscription = this.timerService.trackStateItem$
        .subscribe(res => {
            this.timePosition = res.timePosition;
        });   
     }`
It happens ,using worker-timers, that the variable( this.timePosition) in the app-component does not update. Using the console I realized that the timer-workers works ... so , what am I doing wrong?

**Comment by chrisguttandin** [comment]
Hi @davvoz,

I can't really help you, because I can't see how you push new values to the `trackStateItem$` Subject. It’s hard to tell why it doesn’t emit values without knowing that.

The reason for showing not such a heavy CPU usage when using worker-timers could be that worker-timers are slow by design when using them with a delay of 0. The native implementation usually fires on the tick in that case, whereas worker-timers takes at least the round-trip time to the worker before it will fire the callback.

Maybe that helps to track down the issue.

**Comment by davvoz** [comment]
Hi @chrisguttandin ,
I never apologized for my English, I do it now.
In my Injectable timer service I declare these variables that are used by all the components interfaced to the timer :
`private trackStateSource = new BehaviorSubject<TickResponse>(this.trackStateModel);
  public  trackStateItem$ = this.trackStateSource.asObservable();`
... and then I use .next() , in  my "Polling". As you see in scheduleNote() method (see first post) I used changeStateTrack(pt) method ,this one:
`private changeStateTrack(pt): void {
        this.trackStateSource.next({
            traksAreOn: this.trackStateModel.traksAreOn,
            timePosition: this.steps,
            isStarted: true,
            audioContextTime: pt
        });`.
I repeat that this works fine on normal timers.

Anyway there is a news , a strange one :  a GUI component interfaced to the timer can update when i move the mouse , when i stop moving , it stops graphic update , but not the sound update , that it works great. (can I say OMG?).
Are we talking about Thread?

Also I don't understand completly what you explained to me, because of my bad English  or my bad skills , I don't know.

**Comment by chrisguttandin** [comment]
No worries, I'm not a native speaker myself.

I think I know what could be causing your problem. Angular is using zone.js to patch all native APIs. It does for example patch the native setTimeout function. Whenever the callback of a setTimeout function gets executed, Angular knows that it will have to execute its change detection once that function completes.

Angular (or zone.js) doesn't know anything about worker-timers and it does therefore not run its change detection algorithm in response to an executed callback. If you want to achieve a similar behavior you have to tell Angular manually about the changes.

There is an [article by the guys from thoughtram](https://blog.thoughtram.io/angular/2016/02/01/zones-in-angular-2.html) which explains the concept of zones very nicely. It also shows how to manually trigger the change detection.

**Comment by chrisguttandin** [comment]
Hi @davvoz, I'm glad it works now. I will add a litte paragraph to the README explaining the usage with Angular.

Your solution looks technically correct to me. However I would try to not do UI updates with worker-timers. If possible it might be beneficial to separate UI from sound updates. Then UI updates can be scheduled with requestAnimationFrame and sound updates can be driven by worker-timers.

**Comment by davvoz** [comment]
Thanks for the advice @chrisguttandin . 
I will try to do as you say. Actually I had already tried requestAnimationFrame but it did not work, but now I can try again.
In practice, 2 parallel timers, one for graphics(requestAnimationFrame) and one for sound(workersTimer).
Thanks for everything, people like you make better world.
