### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by secretsounds** [chrisguttandin/worker-timers#165]
Please add a LICENSE.md file containing the project license and copyright. Many users/companies avoid adopting libs without a license file.

**Comment by chrisguttandin** [comment]
Hi @secretsounds, thanks for the feedback. I already planned to add a LICENSE file some time in the future, but I thought it has not such a high priority. The package.json file already specifies the license.

I will add the matching LICENSE file soon.

**Comment by secretsounds** [comment]
Thanks!
