### ISSUE TITLE
source version of worker.ts

### ISSUE THREAD

**Issue by worc** [chrisguttandin/worker-timers#286]
is there an uniminified version of worker.ts? i'm maintaining some code with an older version of worker-timers as a dependency. an unminified source would be helpful in seeing what's changed recently, and what edge cases might exist when upgrading.

**Comment by chrisguttandin** [comment]
Hi @worc,

yes there is an unminified version. This package is actually just a thin wrapper around two other packages to make them easier to consume. Those two packages are [worker-timers-broker](https://github.com/chrisguttandin/worker-timers-broker) and [worker-timers-worker](https://github.com/chrisguttandin/worker-timers-worker).

As part of the build process of this package the content of worker-timers-worker gets bundled into `src/worker/worker.ts`. You could actually do it yourself by running `grunt build`.

I hope this helps. Please let me know if you have further questions.

**Comment by chrisguttandin** [comment]
Hi @worc,

I'm going to close this issue now. Please let me know if you're not considering this issue to be resolved or if you run into any other problems.
