### ISSUE TITLE
SyntaxError: missing ; before statement main.bundle.js

### ISSUE THREAD

**Issue by olastor** [chrisguttandin/worker-timers#39]
I'm using [angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter) and installed your module as described in `README.md`. But when I try to use `worker-timers` anywhere in my code, console gives me

`SyntaxError: missing ; before statement`
`}/* harmony export */ exports["clearInterval"] = clearInterval;`
`main.bundle.js (Zeile 57428, Spalte 22)`

Seems to be some parsing error or something. Unfortunately I'm not very familiar with this at all.

**Comment by chrisguttandin** [comment]
Hi olastor, many thanks for using this package. Unfortunately, I can't exactly tell you what that error means. But I guess it is because worker-timers is meant to be consumed by browserify instead of webpack.

Would it help you, if I provide a bundled and transpiled file along with the source code?

**Comment by chrisguttandin** [comment]
Hi olastor, I hope one of my hints from above worked for you. I'm closing this issue now, but please feel free to reopen it, if you still experience problems.
