### ISSUE TITLE
workerTimers.setInterval() not working in ipad and iphone devices in background

### ISSUE THREAD

**Issue by Ganeshkaredla** [chrisguttandin/worker-timers#413]
Hi @chrisguttandin 

In Javascript setInterval and setTimeout will not work when we change the tab of the browser, To resolve that issue I had used this package. Even I use I observed the same issue with this package as well when we change the tab of the browser in and when we come back the timer was running from where we left or just with a 2-4sec diff.

If this works even though there is some 5-10sec difference is there.

Is this package supports IOS devices?

And I had one more query,  is there any chance to work in local builds and fail in production builds? 

I have used like this :

`import * as workerTimers from 'worker-timers'`
`  this.timerId = workerTimers.setInterval(this.setSeconds, 1000)`

` if (this.timerId) {
         workerTimers.clearInterval(this.timerId)
      }`
      
Testing device version
IOS version 13.7 

Kindly help me out to resolve this issue.
TIA

**Comment by chrisguttandin** [comment]
Hi @Ganeshkaredla,

I'm not aware of any iOS specific problems of this library so far. Is the issue that you are describing only affecting the iOS device or does it also happen on other devices?

It would be great if you have the chance to setup a little example which shows the problem on a service like [StackBlitz](https://stackblitz.com) or [CodePen](https://codepen.io).

**Comment by Ganeshkaredla** [comment]
Hi @chrisguttandin 

Yes , i got this issue in only IOS devices 

For IOS version 14.4 it works fine 
But when i tested in ipad which has IOS 13.7 version i got this issue 
it was not running in background at all

In normal devices it works fine , i observed only in IOS version 13.7

**Comment by chrisguttandin** [comment]
Thanks a lot for providing more information. Unfortunately I don't have an iOS device which runs on iOS v13.x.

Do you get any errors in the console? Does worker-timers work as long as the tab is not in background?

**Comment by HakobiDev** [comment]
@chrisguttandin @Ganeshkaredla AFAIK this is already fixed at latest version of iOS 14 also affected framework called IONIC and they filed a bug report about webworker specific problem in early iOS 14

**Comment by chrisguttandin** [comment]
Thanks for letting us know, @HakobiDev. Do you, by chance, have a link to Apple's bug tracker?

I guess there is not much we can do if it's a browser bug.

**Comment by HakobiDev** [comment]
@chrisguttandin sorry I cannot retrieve the actual bug report, but one thing I know it is already fixed in latest iOS version, and don't be bother :) it is browser specific problem that majority of browser in iOS 14 is dependent on that bug.

**Comment by chrisguttandin** [comment]
Thanks again for your input @HakobiDev. In any case please feel free to reopen this issue if it pops up again.

**Comment by KVPasupuleti** [comment]
@chrisguttandin Great package and thanks for the help. 

I have an `iPhone 11` which works on the latest `14.6` version. As per the discussion above, I understood this issue shouldn't happen after `v14`.

I have tested in both Chrome and Safari, and identified only Chrome has this problem. It seems the IONIC bug fix is only done for Safari.

**Results:**

Browser | Version | When Tab is Inactive | When Browser window is inactive
-- | -- | -- | -- 
Chrome | 91.0.4472.80 | Works Fine | Timer Pauses
Safari | Built-in | Works Fine | Works Fine


I didn't find any issue with Android, Linux, and Windows devices.

Can you please look into this issue? It would be of great help.

**Comment by chrisguttandin** [comment]
Hi @KVPasupuleti,

unfortunately I don't have a device at hand to debug this myself. Could you please check if Chrome fires some [page lifecycle events](https://developers.google.com/web/updates/2018/07/page-lifecycle-api)? I guess if it decides to stop the full page by firing a `'freeze'` or `'pagehide'` event there is not much we can do.

You could also try replacing `worker-timers` with [`audio-context-timers`](https://github.com/chrisguttandin/audio-context-timers). It offers the same API but uses an `AudioContext` internally to schedule events. Please note that the timers need to be scheduled in response to a user gesture to please the autoplay policy.

**Comment by KVPasupuleti** [comment]
> Hi @KVPasupuleti,
> 
> unfortunately I don't have a device at hand to debug this myself. Could you please check if Chrome fires some [page lifecycle events](https://developers.google.com/web/updates/2018/07/page-lifecycle-api)? I guess if it decides to stop the full page by firing a `'freeze'` or `'pagehide'` event there is not much we can do.
> 
> You could also try replacing `worker-timers` with [`audio-context-timers`](https://github.com/chrisguttandin/audio-context-timers). It offers the same API but uses an `AudioContext` internally to schedule events. Please note that the timers need to be scheduled in response to a user gesture to please the autoplay policy.

Tried `audio-context-timers` in iOS device (iPhone 11), setInterval isn't even getting triggered.

**Comment by chrisguttandin** [comment]
Sorry, I should have mentioned that audio-context-timers only works on pages which already unlocked the autoplay policy these days. I assume that wasn't the case and that's why setInterval never called the callback.

Did you test if the 'pagehide' or 'freeze' events get fired in Chrome on your iOS device?
