### ISSUE TITLE
There is no interval scheduled with the given id

### ISSUE THREAD

**Issue by VictorPulzz** [chrisguttandin/worker-timers#415]
Hello, I try using you lib in vue.js, and got some issue:
```
module.js:67 Uncaught Error: There is no interval scheduled with the given id "1".
```
I do not understand why, I am doing everything right ...
Can you help me?
![image](https://user-images.githubusercontent.com/23406402/120610638-0d0e2c00-c45c-11eb-8ef3-f861da76f098.png)

**Comment by chrisguttandin** [comment]
Hi @VictorPullzz,

is it possible that you call `workerTimers.clearInterval(timeInterval)` multiple times with the same `timeInterval`? If so you could fix your code by setting `timeInterval` to `null` after clearing the interval.

```js
stopCurrentTimer: () => {
    if (timeInterval) {
        workerTimers.clearInterval(timeInterval);
        timeInterval = null;
    }
}
```

Calling `workerTimers.clearInterval` with a value that doesn't belong to an active timer throws an error: https://github.com/chrisguttandin/worker-timers#error-handling.

I hope this helps.

**Comment by chrisguttandin** [comment]
Since v8 `worker-timers` should no longer throw an error when calling `clearInterval()` or `clearTimeout()` with an unknown id.
