### ISSUE TITLE
Can't mock any method by jasmine spyOn

### ISSUE THREAD

**Issue by myushchenko** [chrisguttandin/worker-timers#417]
I've try to write Unite Tests on Jasmine and faced with issue that impossible to mock any `method.

```javascript
import * as workerTimers from 'worker-timers';

....
spyOn(workerTimers, 'setInterval').and.returnValue(1);
```

and I got an exception: 
**Error: <spyOn> : setInterval is not declared writable or has no setter**

Also tried another way
```javascript
const setIntervalSpy = spyOnProperty(workerTimers, 'setInterval', 'get').and.returnValue(1);
```

But also didn't help me.

Could you give any advice how I can test it?

**Comment by chrisguttandin** [comment]
Hi @myushchenko, I'm not sure if there is anything we can do to change this behavior. When you set up a spy you are essentially overwriting the module export. I guess that's what isn't allowed.

Do you mind sharing your test? Maybe there is a way to solve the problem by not using a spy or by passing setInterval into your code as a function argument and not using it as an import.

Another option might be to use [worker-timers-mock](https://github.com/chrisguttandin/worker-timers-mock) in your tests. It's basically a mocked version of this package.

**Comment by myushchenko** [comment]
In order to resolve this quickly I've created file workerTimer.ts
```javascript
import * as workerTimers from 'worker-timers';

export const clearInterval = (timerId: number) => workerTimers.clearInterval(timerId);
export const setInterval = (func: () => void, delay: number) => workerTimers.setInterval(func, delay);
```
My unit test
```javascript
import * as workerTimer from './workerTimer';
.........
it('should run timer', () => {
    // arrange
    const setIntervalSpy = spyOn(workerTimer, 'setInterval').and.callFake((func) => {
      func();
      return 1;
    });
    localStorage.setItem(IDLE_WARNING_TIME_OUT, '1000');
    // act
    spectator.detectChanges();
    // assert
    expect(setIntervalSpy).toHaveBeenCalled();
    expect(spectator.component.secondsLeft).toBe(0);
  });
```
And it works, not clear why this not work when use:
```javascript
import * as workerTimer from 'worker-timers';
``` 
it also export  setInterval  and clearInterval.

Thanks, I will try to play with [worker-timers-mock](https://github.com/chrisguttandin/worker-timers-mock) also.

**Comment by chrisguttandin** [comment]
That's interesting, that your local file works but using `worker-timers` directly doesn't. I suppose is has something to do with the transpilation but I don't know this for sure.

I was hoping that you have a function in your code which looks like this ...

```js
import { setInterval } from 'worker-timers';

export const scheduleSomething = () => setInterval(() => {}, 100);
```

You could then write it like ...

```js
export const scheduleSomething = (setInterval) => setInterval(() => {}, 100);
```

Then the tests can pass in the spy from the outside.

But your test looks more like the test of an Angular component. I guess the idea doesn't work there or it least it's not that straightforward.

**Comment by myushchenko** [comment]
Yes, I use angular component.
Now I've resolved my issue.

Thank you, Christoph.

**Comment by chrisguttandin** [comment]
I'm glad it works for you now. Just in case someone else stumbles upon this issue what did you do in the end?
