### ISSUE TITLE
Worker in separate file

### ISSUE THREAD

**Issue by magancete** [chrisguttandin/worker-timers#419]
I need to include the worker in a separate worker.js file on my website but I can't export it from here correctly. What code should I put in worker.js to work with the same functions when initializing it with:

var workerTimers = new Worker ("worker.js");

var intervalId = workerTimers.setInterval (() => {
     // do something many times
}, 100);

**Comment by chrisguttandin** [comment]
Hi @magancete,

luckily this package is a combination of [worker-timers-broker](https://github.com/chrisguttandin/worker-timers-broker) which is what runs on the main thread and [worker-timers-worker](https://github.com/chrisguttandin/worker-timers-worker) which runs on the worker thread. It's absolutely possible to use those two packages directly.

You can include worker-timers-worker in your `worker.js` file. And over on the main thread you can use the `load()` function exported by worker-timers-broker to communicate with the worker.

```js
import { load } from 'worker-timers-broker';

workerTimers = load('worker.js');
```

I hope this helps.
