### ISSUE TITLE
Fallback when webworker not supported?  

### ISSUE THREAD

**Issue by garronej** [chrisguttandin/worker-timers#440]
Hello,

First, thank you for creating this **exceptional** library—I'm genuinely impressed!  
I’m using it in [oidc-spa](https://oidc-spa.dev) and pepole are starting using the lib in android webviews.  

I had a quick question: would it be feasible to fall back to a basic `setTimeout` implementation when the environment doesn’t support web workers?  

Or perhaps this is already in place and I can't read code.  

Thanks again!  

Best regards,

**Comment by chrisguttandin** [comment]
Hi @garronej, thank you for your kind words.

So far I was hesitant to add an automatic fallback. I'm afraid it would cover errors which in turn may result in unexpectedly degraded performance without notice.

That being said, is there no Web Worker support in WebViews on Android? I tried to look it up but wasn't able to find any official information.

**Comment by garronej** [comment]
Thank you for your answer.  

Well actually it seems that it works since pepoles have been reporting oidc-spa working successfully in webview.  
It was the iframe that was problematic.  

Thank you for your answer !
