### ISSUE TITLE
Timeout throttling still apparent

### ISSUE THREAD

**Issue by infojunkie** [chrisguttandin/worker-timers#65]
I must be doing something wrong, because I am still noticing the 1s throttling even though I switched from `window.setTimeout` to your library. 

Here's a little snippet to test:
```javascript
import * as Timer from 'worker-timers';

var time = performance.now();
Timer.setInterval(() => {
  console.log(performance.now() - time);
  time = performance.now();
}, 500);
```

When my tab is focused, the logged interval is around 500. When I switch to another tab and get back to this one a few seconds later, I see logged intervals of around 1000.

Using Chrome Version 55.0.2883.87 (64-bit) on Ubuntu 16.04.

**Comment by infojunkie** [comment]
This may be related: https://bugs.chromium.org/p/chromium/issues/detail?id=646163

**Comment by chrisguttandin** [comment]
Hi @infojunkie, thanks for creating that issue. I'm sorry that it took me so long to respond. I fear that this new behavior of Chrome is intended. I also filed a bug at the Chromium project (https://bugs.chromium.org/p/chromium/issues/detail?id=667272) with a similar example.

In the meantime I started to work on an alternative which seems to work for now. Maybe you want to give it a try: https://github.com/chrisguttandin/audio-context-timers. Please let me know if that works for you.

**Comment by infojunkie** [comment]
Thanks, will take a look there!

**Comment by chrisguttandin** [comment]
Hi @infojunkie, I will close that issue because it looks like the behavior of Chrome (56+) has been changed again. However there is no guarantee that it will not pop up anymore in any browser's future versions. Please feel free to open that issue again or to create a new one if this bug returns.
