### ISSUE TITLE
How to use this in simple JS application?

### ISSUE THREAD

**Issue by malcolmocean** [chrisguttandin/worker-timers#79]
I'm confused by how to use this in my project, because I'm not using typescript or ES6 modules. Can someone package this up as a simple javascript dependency I can use?

**Comment by chrisguttandin** [comment]
Hi @malcolmocean, although it is not explicitly mentioned in the README file, you can also use the module as a CommonJS or AMD module like this:

```js
var workerTimers = require('worker-timers');
```

If you install the module via NPM the universal bundle is located at `/build/es5/bundle.js`.

Does that help? It's pretty hard to guess what you mean by "simple JS application".

**Comment by malcolmocean** [comment]
Ah. That would probably be sufficient. I ended up rolling my own because I wanted it integrated with Angular anyway: [gist here](https://gist.github.com/malcolmocean/567380c149129a93541ffc015c6e63ac)

By simple, in this case I mostly just meant that I'm not using a module framework. I guess my confusion was more that I didn't realize that installing via npm would cause it to build.
