### ISSUE TITLE
Using worker-timers with Web Audio Scheduling

### ISSUE THREAD

**Issue by MVSICA-FICTA** [chrisguttandin/worker-timers#96]
In looking around for way to handle Web Audio scheduling I found worker-timers. Chris Wilson uses a worker in his Metronome example, can worker-timers be used as a replacement? 

http://webaudiodemos.appspot.com/metronome/index.html

Also, I'm interested in finding the optimal way to integrate Web Audio and RxJS. Not sure if a custom RxJS Scheduler is the best option or just wrapping the Web Audio specific scheduling as a side-effect?

**Comment by chrisguttandin** [comment]
Hi @MVSICA-FICTA ,

it is indeed the same technique which Chris is using. Actually Chris was the one who told me about the idea to use a WebWorker for consistent timing.

I don't really know how to built a scheduler with RxJS, but an observable could be created like this:

```js
import { clearInterval, setInterval } from 'worker-timers';
import { Observable } from 'rxjs/Observable';

const workerTimersObservable = new Observable((observer) => {
    const intervalId = setInterval(() => observer.next(), 100);

    return () => {
        clearInterval(intervalId);
    };
});
```

Please let me know if you find a way to use an RxJS scheduler. I would be interested in that as well.

**Comment by MVSICA-FICTA** [comment]
Thanks for the confirmation, worker-timers seems very useful. Presently, I'm stepping through a load of time related aspects across a few API's. Will definitely let you know about the Web Audio scheduler. If you have an email we could communicate that way about ongoing progress...

**Comment by chrisguttandin** [comment]
Yes sure, you can find my email on my company's homepage: [media-codings.com](http://media-codings.com).

I will close this issue now. Please feel free to open a new one if you stumble upon another problem.
